### ISSUE TITLE
Arima HiC support?

### ISSUE THREAD

**Issue by PanZiwei** [JinLabBioinfo/HiCorr#2]
Hi,
Does HiCorr can support [Arima HiC](https://arimagenomics.com/)? If so, how to use it? THX!

**Comment by shanshan950** [comment]
Hi,
Sorry for the late response, HiCorr DPNII mode should work for Arima Hi-C, but there is a change in the reads prepossessing step, I'll include a manual for that very soon.

**Comment by shanshan950** [comment]
> Hi, Does HiCorr can support [Arima HiC](https://arimagenomics.com/)? If so, how to use it? THX!

Hi,
Sorry for the late response, HiCorr DPNII mode should work for Arima Hi-C, but there is a change in the reads prepossessing step, I'll include a manual for that very soon.
